{
 "title": "Technicolor Router",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Device Info",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "technicolor_info" }
   ]
  },
  {
   "title": "Ethernet Ports",
   "type": "status-history",
   "gridPos": { "h": 9, "w": 21, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "sum(technicolor_ports_speed_mbps) by (interface)",
     "legendFormat": "{{ interface }}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "technicolor_uptime_seconds_total"
    }
   ]
  },
  {
   "title": "Ethernet Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  },
  {
   "title": "Received Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pkts" } },
   "targets": [
    {
     "expr": "sum(rate(technicolor_rx_packets_pkts_total{type=\"ethernet\"}[5m])) by (interface)",
     "legendFormat": "{{ port }}"
    }
   ]
  },
  {
   "title": "Received Bandwidth",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(technicolor_rx_packets_pkts_total{type=\"ethernet\"}[5m])) by (interface)",
     "legendFormat": "{{ port }}"
    }
   ]
  },
  {
   "title": "Transmitted Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "pkts" } },
   "targets": [
    {
     "expr": "sum(rate(technicolor_tx_packets_pkts_total{type=\"ethernet\"}[5m])) by (interface)",
     "legendFormat": "{{ port }}"
    }
   ]
  },
  {
   "title": "Transmitted Bandwidth",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(technicolor_tx_packets_pkts_total{type=\"ethernet\"}[5m])) by (interface)",
     "legendFormat": "{{ port }}"
    }
   ]
  },
  { "title": "Wifi Bandwidth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Received Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "pkts" } },
   "targets": [
    {
     "expr": "sum(rate(technicolor_rx_packets_pkts_total{type=\"wifi\"}[5m])) by (interface)",
     "legendFormat": "{{ port }}"
    }
   ]
  },
  {
   "title": "Received Bandwidth",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 31 },
   "targets": [
    {
     "expr": "sum(rate(technicolor_rx_packets_pkts_total{type=\"wifi\"}[5m])) by (interface)",
     "legendFormat": "{{ port }}"
    }
   ]
  },
  {
   "title": "Transmitted Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "pkts" } },
   "targets": [
    {
     "expr": "sum(rate(technicolor_tx_packets_pkts_total{type=\"wifi\"}[5m])) by (interface)",
     "legendFormat": "{{ port }}"
    }
   ]
  },
  {
   "title": "Transmitted Bandwidth",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 41 },
   "targets": [
    {
     "expr": "sum(rate(technicolor_tx_packets_pkts_total{type=\"wifi\"}[5m])) by (interface)",
     "legendFormat": "{{ port }}"
    }
   ]
  }
 ]
}